name: Analyze

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.0

      - name: Install dependencies
        run: dart pub get

      - name: Check formatting
        run: |
          dart format -o none --set-exit-if-changed bin/
          dart format -o none --set-exit-if-changed lib/

      - name: Analyze lib
        run: dart analyze
        working-directory: lib

      - name: Analyze bin
        run: dart analyze
        working-directory: bin

      - name: Run tests
        run: dart run ./bin/pcov.dart --test-command="dart test --coverage=coverage"

      - name: Convert coverage to lcov.info
        run: |
          dart pub global activate coverage
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
